### ISSUE TITLE
In Lab 1 - PodSecurityPolicy deprecated in v1.25

### ISSUE THREAD

**Issue by SliderCO-007** [kensipe/ckad-labs#3]
Hello,

I thought it might be a trick to confuse or to force students to inspect the api-resources extra thoroughly but after grepping through the api-resources output, I consulted kubernetes.io.

[PodSecurityPolicy deprecated page on Kubernetes.io](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/)

So PSP(s) are no longer an API resource as of version 1.25. Perhaps the reference should be removed from the lab?

ENV:
Win11, Git Bash w/ zsh

Kind CLI:
$ kind version                                                                                                                                       1 ↵ 
kind v0.17.0 go1.19.2 windows/amd64

Kubernetes:
$ k version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", Build
Date:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", Build
Date:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.25) exceeds the supported minor version skew of +/-1

**Comment by kensipe** [comment]
thank you @SliderCO-007 !   I will look into upgrading... there are several other things to update as well.
I should have picked a more stable resource to query!
